parameters:
- name: deploymentValidForEnvironment
  type: string
  default: "true"
stages:
- stage: deploy
  displayName: 'Deploy to $(EnvironmentName) Environment'
  jobs:
  - deployment: 
    condition: eq('${{parameters.deploymentValidForEnvironment}}', 'true')
    pool: 
      vmImage: 'windows-2019'
    variables: # The build contains an output variable named TriggerSolutionUpgrade that is used in the deployment steps to determine whether to perform a solution upgrade or update
      TriggerSolutionUpgrade: false
    environment: '$(EnvironmentName)'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Environment Name: $(EnvironmentName)'
          - script: echo 'Valid Value: ${{parameters.deploymentValidForEnvironment}}'
          - script: echo 'PR Branch: variables['System.PullRequest.TargetBranch']'
          - script: echo 'Build Source Branch: Build.SourceBranchName'
          - script: echo 'Prod Source: variables['ProductionSourceBranch']'
          - template: deploy-Solution.yml
            parameters:
              serviceConnection: '$(ServiceConnection)'
              environmentVariables: '$(EnvironmentVariables)'
              connectionReferences: '$(ConnectionReferences)'
              aadGroupTeamConfiguration: '$(AadGroupTeamConfiguration)'
              aadGroupCanvasConfiguration: '$(AadGroupCanvasConfiguration)'
              solutionComponentOwnershipConfiguration: '$(SolutionComponentOwnershipConfiguration)'
