parameters:
- name: RunDeployment
  type: boolean
  default: true
stages:
- stage: deploy
  displayName: 'Deploy to $(EnvironmentName) Environment'
  jobs:
  - deployment: 
    pool: 
      vmImage: 'windows-2019'
    variables: # The build contains an output variable named TriggerSolutionUpgrade that is used in the deployment steps to determine whether to perform a solution upgrade or update
      TriggerSolutionUpgrade: false
    environment: '$(EnvironmentName)'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-Solution.yml
            parameters:
              serviceConnection: '$(ServiceConnection)'
              environmentVariables: '$(EnvironmentVariables)'
              connectionReferences: '$(ConnectionReferences)'
              aadGroupTeamConfiguration: '$(AadGroupTeamConfiguration)'
              aadGroupCanvasConfiguration: '$(AadGroupCanvasConfiguration)'
              solutionComponentOwnershipConfiguration: '$(SolutionComponentOwnershipConfiguration)'
          condition: ${{parameters.RunDeployment}}