steps:
- template: deploy-Solution.yml
parameters:
    serviceConnection: '$(ServiceConnection)'
    environmentVariables: '$(EnvironmentVariables)'
    connectionReferences: '$(ConnectionReferences)'
    aadGroupTeamConfiguration: '$(AadGroupTeamConfiguration)'
    aadGroupCanvasConfiguration: '$(AadGroupCanvasConfiguration)'
    solutionComponentOwnershipConfiguration: '$(SolutionComponentOwnershipConfiguration)'
