parameters:
- name: serviceConnection
  type: string

steps:
- powershell: |
    cd "$(Pipeline.Workspace)"
    dir
    $path = "$(Pipeline.Workspace)/drop/ConfigurationMigrationData.zip"
    $configurationMigrationExists = Test-Path $path
    Write-Host "##vso[task.setvariable variable=ConfigurationMigrationExists]$configurationMigrationExists"
  displayName: 'Check if Configuration Migration Data exists'

- powershell: |
    $configurationMigrationPowerShellVersion = "1.0.0.53"
    Install-Module -Name Microsoft.Xrm.Tooling.ConfigurationMigration -RequiredVersion $configurationMigrationPowerShellVersion -Force
    Import-CrmDataFile -CrmConnection "$(CdsBaseConnectionString)${{parameters.serviceConnection}}" -Datafile "$(Pipeline.Workspace)/drop/ConfigurationMigrationData.zip" -Verbose
  displayName: 'Import Configuration Migration Data'
  condition: and(succeeded(), eq(variables['ConfigurationMigrationExists'], 'True'))
  #skip task if there is no ConfigurationMigrationData in the downloaded artifact