parameters:
- name: serviceConnection
  type: string

steps:
- powershell: |  
    $cmdletVersion = '$(xrmToolingVersion)'
    if(!$cmdletVersion.Contains("xrmToolingVersion")) {
      Write-Host("Installing specified version of Microsoft.Xrm.Tooling.CrmConnector.PowerShell");
      Install-Module -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell -Force -AllowClobber -RequiredVersion $cmdletVersion
    } else {
      Write-Host("Installing latest version of Microsoft.Xrm.Tooling.CrmConnector.PowerShell");
      Install-Module -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell -Force -AllowClobber
    }
    $conn = Get-CrmConnection -ConnectionString "$(CdsBaseConnectionString)${{parameters.serviceConnection}}"
    # Get the Environment name (which is a GUID)
    $environmentId = $conn.EnvironmentId 
    # Set the EnvironmentId as a global variable for use in other templates
    echo "##vso[task.setvariable variable=EnvironmentId]$environmentId"
  displayName: 'Set EnvironmentId'
