parameters:
- name: serviceConnection
  type: string

steps:
- powershell: |  
    $cmdletVersion = '$(xrmToolingVersion)'
    if(!$cmdletVersion.Contains("xrmToolingVersion")) {
      Install-Module -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell -Force -RequiredVersion $cmdletVersion
    } else {
      Install-Module -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell -Force
    }
    Install-Module -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell -Force #-RequiredVersion $(PowerAppsAdminModuleVersion)
    $connstr = "AuthType=ClientSecret;ClientId=$(ClientId);ClientSecret=$(ClientSecret);url=$(CdsBaseConnectionString)" 
    # Get the CrmConnection object which includes the org and environment IDs.
    $conn = Get-CrmConnection -ConnectionString $connstr
    # Get the Environment name (which is a GUID)
    $environmentId = $conn.EnvironmentId 
    # Set the EnvironmentId as a global variable for use in other templates
    echo "##vso[task.setvariable variable=EnvironmentId]$environmentId"
  displayName: 'Set EnvironmentId'
