trigger: none

resources:
    repositories:
    - repository: PowerApps-Language-Tooling
      type: github
      endpoint: GitHub
      name: Microsoft/PowerApps-Language-Tooling

pool:
  vmImage: 'windows-2019'
  demands:
    - msbuild
    - visualstudio
    
steps:
- checkout: PowerApps-Language-Tooling
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'src/PASopa.sln'

- task: VSBuild@1
  displayName: 'Build solution src/PASopa.sln'
  inputs:
    solution: 'src/PASopa.sln'
    platform: 'any cpu'
    configuration: 'release'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\release\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  