trigger:
  branches:
    include:
      - master
  paths:
    include:
      - temp-canvas-packager/*
    exclude:
      - SourceControlHelperConnectors/*.md

pool:
  vmImage: 'windows-2019'
  demands:
    - msbuild
    - visualstudio
    
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'temp-canvas-packager/temp-canvas-packager.sln'

- task: VSBuild@1
  displayName: 'Build solution temp-canvas-packager/temp-canvas-packager.sln'
  inputs:
    solution: 'temp-canvas-packager/temp-canvas-packager.sln'
    platform: 'any cpu'
    configuration: 'release'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\release\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\temp-canvas-packager\temp-canvas-packager\bin\Release'
  condition: succeededOrFailed()


